# Generated by Django 3.2.8 on 2021-10-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Thể loại của bài đọc', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categores',
            },
        ),
        migrations.CreateModel(
            name='ReadingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên bài đọc', max_length=200)),
                ('read_write', models.CharField(help_text='Nội dung bài đọc', max_length=10000)),
                ('name_id', models.CharField(help_text='ID của bài đọc', max_length=10)),
                ('author', models.CharField(blank=True, help_text='Tên tác giả', max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reading.category')),
            ],
        ),
    ]
