# Generated by Django 3.2.8 on 2021-10-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingbook',
            name='read_write',
            field=models.TextField(help_text='Nội dung bài đọc'),
        ),
    ]
