# Generated by Django 3.2.8 on 2021-11-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0004_auto_20211109_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingbook',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
