# Generated by Django 3.2.8 on 2021-11-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0006_alter_readingbook_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingbook',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
