# Generated by Django 3.2.8 on 2021-11-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0007_alter_readingbook_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingbook',
            old_name='read_write',
            new_name='content_reading',
        ),
        migrations.RemoveField(
            model_name='readingbook',
            name='image',
        ),
    ]
