# Generated by Django 3.2.8 on 2021-11-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0009_auto_20211116_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingbook',
            name='question_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Reading.quesmodel'),
        ),
    ]
