# Generated by Django 3.2.8 on 2021-11-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0011_auto_20211116_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='readingbook',
            name='name_id',
        ),
    ]
