# Generated by Django 3.2.8 on 2021-11-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0012_auto_20211117_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbook',
            name='reading_translate',
            field=models.TextField(help_text='Nội dung bài đọc', null=True),
        ),
    ]
