# Generated by Django 3.2.8 on 2021-11-17 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0014_quesmodel_id_qs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='reading_id',
            new_name='id_read',
        ),
        migrations.RemoveField(
            model_name='quesmodel',
            name='id_qs',
        ),
        migrations.AddField(
            model_name='readingbook',
            name='id_read',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
