# Generated by Django 3.2.8 on 2021-11-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reading', '0015_auto_20211117_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='id_read',
            new_name='name_read',
        ),
        migrations.RemoveField(
            model_name='readingbook',
            name='id_read',
        ),
    ]
