# Generated by Django 3.2.8 on 2021-11-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idiom4Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiom_sentence', models.CharField(max_length=100)),
                ('idiom_meaning', models.CharField(max_length=1000)),
            ],
        ),
    ]
