# Generated by Django 3.2.8 on 2021-11-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usefulModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Thể loại của bài đọc', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categores',
            },
        ),
        migrations.CreateModel(
            name='ReadingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên bài đọc', max_length=200)),
                ('content_reading', models.TextField(help_text='Nội dung bài đọc')),
                ('reading_translate', models.TextField(help_text='Nội dung bài đọc', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usefulModels.category')),
            ],
        ),
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('name_read', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usefulModels.readingbook')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
