# Generated by Django 3.2.8 on 2021-11-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usefulModels', '0002_category_quesmodel_readingbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Nội dung cần ghi nhớ !', null=True)),
                ('name_read', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usefulModels.readingbook')),
            ],
        ),
    ]
